# Generated by Django 3.0.3 on 2020-03-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userbase_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
