# Generated by Django 3.0.3 on 2020-03-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_appointment_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='last_name',
        ),
    ]
